version: '3.8'
services:
  citysc_bot:
    build: .
    volumes:
      - ${BOT_BASE_PATH:-/opt/citysc_bot}:/citysc_bot
    environment:
      - TZ=America/Chicago
      - INIT_DIR=${BOT_BASE_PATH:-/opt/citysc_bot}
    restart: unless-stopped