from typing import Optional
from pydantic import BaseModel, ConfigDict

class AdvancedStats(BaseModel):
    """Model for team advanced stats object from stats API call"""
    model_config = ConfigDict(extra="ignore", strict=False)

    ball_recovery_time: Optional[float] = None
    passes_from_open_play_successful: Optional[int] = None
    x_pass: Optional[float] = None
    passing_performance: Optional[float] = None
    difficult_passes: Optional[int] = None
    difficult_passes_successful_ratio: Optional[float] = None
    difficult_passes_share: Optional[float] = None
    team_average_pressure_count: Optional[float] = None

class TeamStats(BaseModel):
    """Model for team stats object from stats API call"""
    model_config = ConfigDict(extra="ignore", strict=False)

    team_id: str
    team_name: str
    scope: Optional[str] = None
    three_letter_code: Optional[str] = None
    team_three_letter_code: Optional[str] = None
    team_short_name: Optional[str] = None
    team_role: str
    counter_attacks: Optional[int] = None
    substitutions_in: Optional[int] = None
    substitutions_out: Optional[int] = None
    cards_yellow: Optional[int] = None
    cards_yellow_red: Optional[int] = None
    cards_red: Optional[int] = None
    sendings_off: Optional[int] = None
    offsides: Optional[int] = None
    fouls_against_opponent: Optional[int] = None
    fouls_other: Optional[int] = None
    fouls_hand_ball: Optional[int] = None
    fouls_sum: Optional[int] = None
    other_player_actions: Optional[int] = None
    goals: Optional[int] = None
    shots_at_goal_held: Optional[int] = None
    shots_at_goal_wide: Optional[int] = None
    shots_at_goal_crossbar: Optional[int] = None
    shots_at_goal_post: Optional[int] = None
    shots_at_goal_blocked: Optional[int] = None
    shots_at_goal_other: Optional[int] = None
    shots_at_goal_failed: Optional[int] = None
    shots_at_goal_right_leg: Optional[int] = None
    shots_at_goal_left_leg: Optional[int] = None
    shots_at_goal_head: Optional[int] = None
    shots_at_goal_body: Optional[int] = None
    shots_at_goal_no_head: Optional[int] = None
    shots_at_goal_sum: Optional[int] = None
    shots_at_goal_inside_box: Optional[int] = None
    shots_at_goal_outside_box: Optional[int] = None
    assists: Optional[int] = None
    second_assists: Optional[int] = None
    first_and_second_assists: Optional[int] = None
    passes_from_play_successful: Optional[int] = None
    passes_from_play_not_successful: Optional[int] = None
    passes_from_play_sum: Optional[int] = None
    passes_from_standards_successful: Optional[int] = None
    passes_from_standards_not_successful: Optional[int] = None
    passes_from_standards_sum: Optional[int] = None
    passes_successful_sum: Optional[int] = None
    passes_not_successful_sum: Optional[int] = None
    passes_sum: Optional[int] = None
    crosses_from_play_successful: Optional[int] = None
    crosses_from_play_not_successful: Optional[int] = None
    crosses_from_play_sum: Optional[int] = None
    crosses_from_standards_successful: Optional[int] = None
    crosses_from_standards_not_successful: Optional[int] = None
    crosses_from_standards_sum: Optional[int] = None
    crosses_successful_sum: Optional[int] = None
    crosses_not_successful_sum: Optional[int] = None
    crosses_sum: Optional[int] = None
    passes_and_crosses_from_play_successful: Optional[int] = None
    passes_and_crosses_from_play_not_successful: Optional[int] = None
    passes_and_crosses_from_play_sum: Optional[int] = None
    passes_and_crosses_from_standards_successful: Optional[int] = None
    passes_and_crosses_from_standards_not_successful: Optional[int] = None
    passes_and_crosses_from_standards_sum: Optional[int] = None
    passes_and_crosses_successful_sum: Optional[int] = None
    passes_and_crosses_not_successful_sum: Optional[int] = None
    passes_and_crosses_sum: Optional[int] = None
    own_goals: Optional[int] = None
    own_goals_prevented: Optional[int] = None
    defensive_clearances: Optional[int] = None
    abandonments_of_ball: Optional[int] = None
    other_ball_actions: Optional[int] = None
    throw_ins: Optional[int] = None
    penalties_successful: Optional[int] = None
    penalties_not_successful: Optional[int] = None
    penalties_sum: Optional[int] = None
    corner_kicks_left: Optional[int] = None
    corner_kicks_right: Optional[int] = None
    corner_kicks_sum: Optional[int] = None
    free_kicks_direct: Optional[int] = None
    free_kicks_indirect: Optional[int] = None
    free_kicks_sum: Optional[int] = None
    kickoffs_after_goal: Optional[int] = None
    kickoffs: Optional[int] = None
    ball_control_phases: Optional[int] = None
    tackling_games_air_won: Optional[int] = None
    tackling_games_air_lost: Optional[int] = None
    tackling_games_air_sum: Optional[int] = None
    ball_actions: Optional[int] = None
    game_openings_throwout: Optional[int] = None
    game_openings_hand: Optional[int] = None
    game_openings_successful: Optional[int] = None
    game_openings_not_successful: Optional[int] = None
    game_openings_sum: Optional[int] = None
    goalkeeper_saves: Optional[int] = None
    interceptions_left: Optional[int] = None
    interceptions_right: Optional[int] = None
    interceptions_held: Optional[int] = None
    interceptions_fisted: Optional[int] = None
    interceptions_rebounded: Optional[int] = None
    interceptions_cross: Optional[int] = None
    interceptions_corner: Optional[int] = None
    interceptions_sum: Optional[int] = None
    distance_covered: Optional[float] = None
    maximum_speed: Optional[float] = None
    goal_opportunities: Optional[int] = None
    chances: Optional[int] = None
    sitters: Optional[int] = None
    setups_origin_left: Optional[int] = None
    setups_origin_inside_left: Optional[int] = None
    setups_origin_inside_right: Optional[int] = None
    setups_origin_right: Optional[int] = None
    nutmegs: Optional[int] = None
    shots_on_target: Optional[int] = None
    spectacular_plays: Optional[int] = None
    shots_on_goal_suffered: Optional[int] = None
    fouls_suffered: Optional[int] = None
    passes_from_open_play_short: Optional[int] = None
    passes_from_open_play_short_successful_ratio: Optional[float] = None
    passes_from_open_play_medium: Optional[int] = None
    passes_from_open_play_medium_successful_ratio: Optional[float] = None
    passes_from_open_play_long: Optional[int] = None
    passes_from_open_play_long_successful_ratio: Optional[float] = None
    penalties_saved: Optional[int] = None
    penalties_caused: Optional[int] = None
    goals_conceded: Optional[int] = None
    shots_faced: Optional[int] = None
    xG: Optional[float] = None
    xG_efficiency: Optional[float] = None
    playing_time_gross: Optional[int] = None
    playing_time_net: Optional[int] = None
    shots_conversion_rate: Optional[float] = None
    passes_from_play_conversion_rate: Optional[float] = None
    passes_from_standards_conversion_rate: Optional[float] = None
    passes_conversion_rate: Optional[float] = None
    crosses_conversion_rate: Optional[float] = None
    crosses_from_play_conversion_rate: Optional[float] = None
    advanced_stats: AdvancedStats